Se movio la verificacion de la fecha del controler al servicio, y se …
PDSDotNet/AspNetCoreTodo2 pull request #2
Opened 2018-12-07 01:11 UTC by PDSDotNet

…creo un test para dicha condicion.

Se agrego una nueva Vista-Controlador-Servicio para mostrar los Todos finalizados

Se des Humanizo() la feche de DueAt, para ver la fecha en concreto.

Se ordenaron las listas de Todo's, para que en TareasPendientes aparezcan arriba los Todo's vencidos y luego los que esten por vencer, y en TareasFinalizadas aparezcan ordenados por fecha.

Se igualo la cosmetica de la ListaDeUsuarios a la de los Todo's.

Se se agrego una funcion privada que genere la lista de usuarios y la grabe en el ViewBag y es llamada por las Index().

Se automatizo el DropDownList de usuario (y se sacó el botón de enviar). También se modificó el aspecto y posición del DropDownList.

Se pudo sobrecargar al Controller, se le agregaron dos funciones, una que obtiene la lista de usuarios y la graba en el ViewBag, y la otra que obtiene el usuario seleccionado.

Se cambio el nombre de la clase _Controller a BaseControler

Se cambio el nombre del archivo _Controller.cd a BaseControler.cd (me olvide), y se agregaron las anotations [ValidateAntiForgeryToken] y [Authorize] a BaseControler

Borrado de archivos no necesarios

2018-12-09 01:55 UTC, ivanfranco502 approved these changes

2018-12-09 01:55 UTC, ivanfranco502 commented on AspNetCoreTodo/Controllers/HomeController.cs
> +            //ViewData["Message"] = "Your contact page.";
@PDSDotNet no es una buena práctica subir código comentado.

2018-12-09 01:55 UTC, ivanfranco502 commented on AspNetCoreTodo/Controllers/TodoController.cs
> +        public async Task<IActionResult> Index(/*bool completedItems = false*/)
@PDSDotNet ídem código comentado.

2018-12-09 01:55 UTC, ivanfranco502 commented on AspNetCoreTodo/Services/TodoItemService.cs
> +            //return await _context.Items.Where(x => x.IsDone == false && x.UserId == user.Id).ToArrayAsync();
@PDSDotNet ídem comentado.

2018-12-09 03:47 UTC, ivanfranco502 reviewed
Revisar todo lo comentado, para que funcione correctamente la app. Una vez modificado (para probar la nueva funcionalidad), me topé con que no anda el alta.

2018-12-09 03:47 UTC, ivanfranco502 commented on AspNetCoreTodo/Controllers/TodoController.cs
> +            }
```suggestion
            }
```
Está haciendo que no compile la solución

2018-12-09 03:47 UTC, ivanfranco502 commented on AspNetCoreTodo/Controllers/TodoController.cs
> +            var items = await _todoItemService.GetIncompletItemsAsync(currentUser);
`items` ya fue definida antes.

2018-12-09 03:47 UTC, ivanfranco502 commented on AspNetCoreTodo/Controllers/BaseController.cs
> +                if (todo.Usuarios == null)
TodoViewModel no contiene una definición de Usuarios.

2018-12-09 03:47 UTC, ivanfranco502 commented on AspNetCoreTodo/Controllers/TodoController.cs
> +                currentUser = null;
Falta algo de lógica acá, está haciendo que rompa la APP.

2018-12-09 03:48 UTC, ivanfranco502 requested changes
Verificar comentarios anteriores

2018-12-10 16:22 UTC, PDSDotNet commented
Ivan no se que paso, el programa compilaba correctamente antes de hacer el "rebase" que hicimos el ultimo jueves. Lo del código comentado tenes razón es un vicio mido. Ahora estoy en un curso en EEUU, hoy por la tarde me fijo que es lo que pasa y te lo envió nuevamente.
Saludos

2018-12-11 01:13 UTC, PDSDotNet commented
Ivan, estaban faltando algunas lineas de código (las marque con 2018-12-10 FixNewFeatures) en TodoItemService.cs, TodoControler.cs y TodoViewModel.cs.
También borre el código comentado (el que me di cuenta, ya que para es normal comentar código para el futuro).

2018-12-18 00:25 UTC, merged

2018-12-18 00:25 UTC, ivanfranco502 commented
@PDSDotNet Felicitaciones Pablo, muy buen trabajo.

2018-12-18 13:28 UTC, PDSDotNet commented
Muchas gracias Ivan, feliz navidad y año nuevo